server:
  port: 8443
  ssl:
    enabled: true
    key-alias: reduz
    key-store: classpath:keystore/springboot.p12
    key-store-type: pkcs12
    key-store-password: password
    key-password: password